language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t kulram/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true kulram/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-1-958143693995"
    bucket_path: "docker-react"
    on: 
        branck: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRECT_KEY